# fly.toml app configuration file for vinbot-decoder

app = 'vinbot-decoder'
primary_region = 'ewr'

[build]

# VM resources
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Define the long-running bot process (no inbound HTTP service needed)
[processes]
  bot = "python -m vinbot"

# Service configuration for health checks
[[services]]
  processes = ["bot"]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

# Optional: enable machines platform auto features if desired
[experimental]
  auto_rollback = true