# fly.toml app configuration file generated for vinbot-decoder

app = 'vinbot-decoder'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['bot']

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "10s"

[processes]
  bot = 'python -m src.main'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['bot']
