# fly.toml app configuration file for VIN Decoder with Dashboard

app = 'vinbot-decoder-v2'
primary_region = 'ewr'

[build]

# Web Dashboard Service (handles external HTTP traffic)
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['web']

[[http_service.checks]]
  interval = "30s"
  grace_period = "30s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "10s"

# Internal health check service for bot
[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["bot"]

[processes]
  web = './web-entrypoint.sh'
  bot = './entrypoint.sh'

# Web dashboard VM configuration
[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['web']

# Telegram bot VM configuration  
[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['bot']
