"""Initial schema with users and vehicles tables

Revision ID: 0be40f2a767c
Revises: 
Create Date: 2025-08-11 14:22:35.619100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be40f2a767c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PREMIUM', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('service_used', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('basic_info', sa.JSON(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('safety_ratings', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('decoded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_index('idx_make_model_year', 'vehicles', ['make', 'model', 'year'], unique=False)
    op.create_index('idx_vin_expires', 'vehicles', ['vin', 'expires_at'], unique=False)
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=True)
    op.create_table('user_vin_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('decoded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_vin_history_user_id_users')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_user_vin_history_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_vin_history'))
    )
    op.create_index('idx_user_history', 'user_vin_history', ['user_id', 'decoded_at'], unique=False)
    op.create_index('idx_user_vin', 'user_vin_history', ['user_id', 'vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_vin', table_name='user_vin_history')
    op.drop_index('idx_user_history', table_name='user_vin_history')
    op.drop_table('user_vin_history')
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.drop_index('idx_vin_expires', table_name='vehicles')
    op.drop_index('idx_make_model_year', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
